version: '3'
services:
    db: 
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
        volumes:
            - ./db:/db
    es:
        image: elasticsearch:8.3.2
        restart: always
        environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
   
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
            - "9202:9200"
        volumes:
            - ./es:/es
    rmq:
        image: rabbitmq:3.9.11-management
        restart: always
        volumes:
          - ./volumes/rabbitmq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_NODE_TYPE=stats
            - RABBITMQ_NODE_NAME=rabbit@stats
            - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
            - RABBITMQ_DEFAULT_USER=rabbitmquser
            - RABBITMQ_DEFAULT_PASS=rabbitmquser
        # ports:
        #     - "4369:4369"
        #     - "5672:5672"
        #     - "15672:15672"
        #     - "25672:25672"
        #     - "35197:35197"
    app: 
        build: .
        command: bash -c "build-scripts/container/web"
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
            - es
            - rmq
        environment:
            RAILS_ENV: development
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            ES_HOST: es
            RABBITMQ_HOST: rmq

