version: '3'
services:
    db: 
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
        volumes:
            - ./db:/db
    app: 
        build: .
        command: bash -c "build-scripts/container/web"
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        environment:
            RAILS_ENV: development
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db

